### ISSUE TITLE
"cannot load ... redcarpet" running Jekyll locally

### ISSUE THREAD

**Issue by kenny-evitt** [LightTable/lighttable.com#8]
I cloned the repo and completed the two steps in [the _Setup_ section](https://github.com/LightTable/lighttable.com/blob/c7b66916d746719bce4252b31b2df6e9d413da00/README.md#setup) of [the README for this repo](https://github.com/LightTable/lighttable.com/blob/c7b66916d746719bce4252b31b2df6e9d413da00/README.md):

> - `gem install jekyll albino`
> - `jekyll server -w`

When I run `jekyll server -w` I get the following output:

```
Configuration file: /home/kenny/@code/lighttable.com/_config.yml
/home/kenny/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- redcarpet (LoadError)
    from /home/kenny/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /home/kenny/@code/lighttable.com/_plugins/redcarpet2_markdown.rb:3:in `<top (required)>'
    from /home/kenny/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /home/kenny/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /home/kenny/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.0/lib/jekyll/plugin_manager.rb:75:in `block (2 levels) in require_plugin_files'
    from /home/kenny/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.0/lib/jekyll/plugin_manager.rb:74:in `each'
    from /home/kenny/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.0/lib/jekyll/plugin_manager.rb:74:in `block in require_plugin_files'
    from /home/kenny/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.0/lib/jekyll/plugin_manager.rb:73:in `each'
    from /home/kenny/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.0/lib/jekyll/plugin_manager.rb:73:in `require_plugin_files'
    from /home/kenny/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.0/lib/jekyll/plugin_manager.rb:18:in `conscientious_require'
    from /home/kenny/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.0/lib/jekyll/site.rb:97:in `setup'
    from /home/kenny/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.0/lib/jekyll/site.rb:49:in `initialize'
    from /home/kenny/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.0/lib/jekyll/commands/build.rb:30:in `new'
    from /home/kenny/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.0/lib/jekyll/commands/build.rb:30:in `process'
    from /home/kenny/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.0/lib/jekyll/commands/serve.rb:26:in `block (2 levels) in init_with_program'
    from /home/kenny/.rvm/gems/ruby-2.2.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
    from /home/kenny/.rvm/gems/ruby-2.2.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
    from /home/kenny/.rvm/gems/ruby-2.2.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
    from /home/kenny/.rvm/gems/ruby-2.2.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
    from /home/kenny/.rvm/gems/ruby-2.2.1/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
    from /home/kenny/.rvm/gems/ruby-2.2.1/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
    from /home/kenny/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.0/bin/jekyll:17:in `<top (required)>'
    from /home/kenny/.rvm/gems/ruby-2.2.1/bin/jekyll:23:in `load'
    from /home/kenny/.rvm/gems/ruby-2.2.1/bin/jekyll:23:in `<main>'
    from /home/kenny/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
    from /home/kenny/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
```

I installed _redcarpet_ with `gem install redcarpet` and then re-ran `jekyll server -w`; still no luck:

```
Configuration file: /home/kenny/@code/lighttable.com/_config.yml
            Source: /home/kenny/@code/lighttable.com
       Destination: /home/kenny/@code/lighttable.com/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
  Dependency Error: Yikes! It looks like you don't have pygments or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- pygments' If you run into trouble, you can find helpful resources at http://jekyllrb.com/help/! 
  Conversion error: Jekyll::Converters::Markdown encountered an error while converting '_posts/2012-12-11-anatomy-of-a-knockout.md':
                    pygments
             ERROR: YOUR SITE COULD NOT BE BUILT:
                    ------------------------------------
                    pygments
```

Okay, I tried to install the _pygments_ Gem – `gem install pygments` – but:

```
ERROR:  Could not find a valid gem 'pygments' (>= 0) in any repository
ERROR:  Possible alternatives: pigments, rygments, pigment, rb-pygments, segments
```

Oh, okay, apparently the correct Gem install command should be `gem install pygments.rb` – that worked. Finally, I was able to run `jekyll server -w` and access the site locally.

**Comment by kenny-evitt** [comment]
@cldwalker @rundis I haven't done enough Ruby work recently to know why the instructions in the _README_ didn't work. Maybe the missing Gems were added to Jekyll since the instructions were last updated? Should I just add the extra packages to the `gem install ...` command in the instructions? Or should I report upstream issues?

**Comment by kenny-evitt** [comment]
Possibly related, but neither the _redcarpet_ or `pygments.rb` Gems seem to be able to be installed on one of my Windows 7 computers that's running the (Chef supplied) Ruby, version 1.9.3p484.

**Comment by PabloEzequiel** [comment]
Hello, I have the same problem, and the solution was 
`gem install pygments.rb`
After that, **jekyll serve** wotk ok
